### ISSUE TITLE
executable file not found

### ISSUE THREAD

**Issue by eskp** [docker-library/kibana#15]
Hi there,

I'm getting "error: exec: "kibana" executable file not found in $PATH"

Running the container with "docker run -it --name kibana -p 5601:5601 --link elasticsearch kibana"

This is on RHEL 6.7

I have tried on CentOS 6.5 and the container runs successfully.

Docker version 1.7.1

**Comment by tianon** [comment]
Sorry for the delay!  Sounds like something strange with RHEL 6.7 -- I'd suggest getting in touch with RHEL support and seeing whether they've seen anything similar and can help debug further.
