### ISSUE TITLE
Ability to set a default dashboard (or really any defaultAppId)

### ISSUE THREAD

**Issue by delfuego** [docker-library/kibana#16]
Would there be any way to modify the entrypoint so that it looked for an environment variable containing an alternative default app to run at launch, and modify the kibana.yml file accordingly? The ideal would be to be able to do something along the lines of `docker run --name kibana -e DEFAULT_APP_ID="dashboard/my-custom-dashboard" -p 5601:5601 -d kibana` and have that work...

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
