### ISSUE TITLE
4.1.3 tag not found

### ISSUE THREAD

**Issue by delfuego** [docker-library/kibana#19]
Despite [the official Docker Hub page](https://hub.docker.com/_/kibana/) saying that 4.1.3 is a supported tag, it doesn't actually appear to exist — it's not listed [on the tags page](https://hub.docker.com/r/library/kibana/tags/), nor is it in [the Github tag details page](https://github.com/docker-library/docs/blob/master/kibana/tag-details.md). Is there a process by which that tag needs to be populated in the hub?

(Given that Elastic is billing this as an important security update, I'd like to be able to update to it...)

**Comment by tianon** [comment]
Hey, sorry about that -- it did get pushed, but the build was delayed a little bit; can you confirm that you're able to pull it down?

**Comment by delfuego** [comment]
Confirmed!
