### ISSUE TITLE
Please support KIBANA_INDEX to allow specify kibana index

### ISSUE THREAD

**Issue by garyelephant** [docker-library/kibana#25]
Please support KIBANA_INDEX to allow specify kibana index, like:
https://hub.docker.com/r/bobrik/kibana/

This is a very import and common config.

**Comment by Shifter2600** [comment]
+1
When running multiple Kibana Dockers against one ES it is very important that each Kibana have it's own Index

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
