### ISSUE TITLE
Override any setting in kibana.yml via docker command line or environment variable

### ISSUE THREAD

**Issue by jverhoeven** [docker-library/kibana#28]
I need to change the server.basePath config variable and don't want to write to clone the official repo. Right now only the elasticsearch config can be changed, but I propose to extend the 'sed' to include any variable in kibana.yml. Thanks.

**Comment by sfossen** [comment]
I've submitted a pull request for the basepath change

**Comment by jonkri** [comment]
It would be nice to be able to set username and password for HTTP auth somehow too. What I did for now was to volume in a second kibana.yml file (not overwriting the kibana.yml file in the container, which breaks the sed command) and load that file with the <code>--config</code> command-line parameter to the Kibana executable.

**Comment by renich** [comment]
I need this as well. basePath is essential if your mounting kibana on another app.

**Comment by myoung34** [comment]
Also need so I can use Shield plugin

**Comment by bartwalczak1** [comment]
+1

**Comment by myoung34** [comment]
@tianon how do we go about bumping these things? there are some open PR's (mine included) that solve this kind of stuff with no love

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
