### ISSUE TITLE
Kibana Docker image should ship with "optimized code"

### ISSUE THREAD

**Issue by multani** [docker-library/kibana#31]
When starting a freshly pulled Kibana image from the registry, we get the following message:

```
{"type":"log","@timestamp":"2016-01-27T11:03:24+00:00","tags":["info","optimize"],"pid":1,"message":"Optimizing and caching bundles for kibana and statusPage. This may take a few minutes"}
{"type":"log","@timestamp":"2016-01-27T11:03:50+00:00","tags":["info","optimize"],"pid":1,"message":"Optimization of bundles for kibana and statusPage complete in 26.08 seconds"}
```

Would it be possible to ship the Docker image with this optimization phase already done? This would save some CPU cycles, allow to scale Kibana on new instances faster and allow the deployment inside read-only containers more straightforward.

**Comment by yosifkit** [comment]
I'm going to need more information on how you are running this. It seems to start very quickly here:

``` console
$ docker run -d --name elasticsearch elasticsearch
$ docker run -it --rm -e ELASTICSEARCH_URL=http://elasticsearch.docker:9200 kibana
  log   [23:30:24.933] [info][status][plugin:kibana] Status changed from uninitialized to green - Ready
  log   [23:30:24.946] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
  log   [23:30:24.952] [info][status][plugin:kbn_vislib_vis_types] Status changed from uninitialized to green - Ready
  log   [23:30:24.953] [info][status][plugin:markdown_vis] Status changed from uninitialized to green - Ready
  log   [23:30:24.955] [info][status][plugin:metric_vis] Status changed from uninitialized to green - Ready
  log   [23:30:24.956] [info][status][plugin:spyModes] Status changed from uninitialized to green - Ready
  log   [23:30:24.957] [info][status][plugin:statusPage] Status changed from uninitialized to green - Ready
  log   [23:30:24.958] [info][status][plugin:table_vis] Status changed from uninitialized to green - Ready
  log   [23:30:24.966] [info][listening] Server running at http://0.0.0.0:5601
  log   [23:30:30.003] [info][status][plugin:elasticsearch] Status changed from yellow to yellow - No existing Kibana index found
  log   [23:30:32.795] [info][status][plugin:elasticsearch] Status changed from yellow to green - Kibana index ready
```

**Comment by multani** [comment]
Ah I see, I get the same result running your example.

I'm actually using a small custom configuration file, which sets a couple of settings (most notably `server.basePath`) and this file is mounted over the container's one:

```
$ docker run -it --rm -v $PWD/kibana.yml:/opt/kibana/config/kibana.yml kibana:4.3.1
warning: missing ELASTICSEARCH_PORT_9200_TCP or ELASTICSEARCH_URL
  Did you forget to --link some-elasticsearch:elasticsearch
  or -e ELASTICSEARCH_URL=http://some-elasticsearch:9200 ?

  log   [08:31:04.623] [info][optimize] Optimizing and caching bundles for kibana and statusPage. This may take a few minutes
  log   [08:31:28.678] [info][optimize] Optimization of bundles for kibana and statusPage complete in 24.05 seconds
  log   [08:31:28.693] [info][status][plugin:kibana] Status changed from uninitialized to green - Ready
  log   [08:31:28.711] [info][status][plugin:elasticsearch] Status changed from uninitialized to yellow - Waiting for Elasticsearch
```

**Comment by treksler** [comment]
Is there a way to manually trigger optimizing and caching bundles for kibana and statusPage?
If you put your custom config in a docker image and were able to RUN whatever command that does the optimization and caching in that Dockerfile, then the resulting image should start very quickly

**Comment by smousa** [comment]
https://github.com/elastic/kibana/issues/6057

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
