### ISSUE TITLE
Kibana connects to http://localhost:9200 instead of http://elasticsearch:9200 as advertised in documentation

### ISSUE THREAD

**Issue by jpetazzo** [docker-library/kibana#35]
The doc for the image says:

```
$ docker run --link some-elasticsearch:elasticsearch -d kibana
```

But then when connecting to Kibana, it complains that it cannot connect to `http://localhost:9200`.

Adding `ELASTICSEARCH_URL=http://elasticsearch:9200` to the environment does the trick.

I don't know if we want to provide that as a default env var, or update the docs, or both, but something has to be done :-)

**Comment by 9monsters** [comment]
I got the same error , `warning: missing ELASTICSEARCH_PORT_9200_TCP or ELASTICSEARCH_URL
  Did you forget to --link some-elasticsearch:elasticsearch
  or -e ELASTICSEARCH_URL=http://some-elasticsearch:9200 ?`

**Comment by arthurtsang** [comment]
just linking it doesn't work, you'll also have to add the ELASTICSEARCH_URL env variable, but since the containers are linked you can use the link in the url.

**Comment by tianon** [comment]
This should've been fixed by https://github.com/docker-library/kibana/pull/44. :+1:

**Comment by apetrovYa** [comment]
Playing with a cluster of elasticsearch nodes and a kibana, I come across the same problem "No connection between the two". After some trying and information gathering about the issue I realized that using the following command

 `docker run --link my-defined-network:elasticsearch -e "ELASTICSEARCH=http://host_ip:9200" -d kibana `

makes possible the connection and kibana is able to connect to the elasticsearch.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
