### ISSUE TITLE
No cleanup is performed - reduce the image size, please.

### ISSUE THREAD

**Issue by wheredevel** [docker-library/kibana#40]
At least:
RUN apt-get clean && rm -rf /var/lib/apt/lists/\* /tmp/\* /var/tmp/*

**Comment by yosifkit** [comment]
`apt-get clean` is already [built into `apt-get update`](https://github.com/docker/docker/blob/03e2923e42446dbb830c654d0eec323a0b4ef02a/contrib/mkimage/debootstrap#L82-L105) and the other directories you mention don't have anything:

``` console
$ docker run -it --rm --name my-kibana kibana bash
root@293711462f7e:/# apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
root@293711462f7e:/# rm /etc/passwd
root@293711462f7e:/# 

$ # in new terminal
$ docker diff my-kibana
C /etc
D /etc/passwd
```

**Comment by wheredevel** [comment]
Got it.
