### ISSUE TITLE
Install Sense

### ISSUE THREAD

**Issue by gfelot** [docker-library/kibana#47]
I'm trying to install the sense plugin with
`docker run --name kibana --link elasticsearch:elasticsearch -d kibana -p 5601:5601 --plugin elastic/sense`

But when I hit : http://192.168.99.100:5601/app/sense

I got : 
`{"statusCode":404,"error":"Not Found","message":"Unknown app sense"}`

(Also the port the exposing of the port doesn't work, I have to set it up with Kitematic)

**Comment by treksler** [comment]
I would recommend creating your own docker image that inherits from the official image, if you want to install plugins. Something like this. 

Make a Dockerfile in a new folder called mykibana

Dockerfile

```
FROM kibana:4.5
RUN gosu kibana /opt/kibana/bin/kibana plugin --install elastic/sense
```

docker build -t mykibana:4.5 .
docker run --name kibana --link elasticsearch:elasticsearch -p 5601:5601 -d mykibana:4.5

**Comment by robin-maxxton** [comment]
You could also run `docker exec <name> <cmd>` after the `docker run` command and use the kibana-plugin command

For example
`docker exec kibana kibana-plugin install sense`

https://www.elastic.co/guide/en/kibana/current/_installing_plugins.html

**Comment by denov** [comment]
fyi - sense is built into 5.x

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
