### ISSUE TITLE
Failed to generate PDF reporting using kibana latest docker

### ISSUE THREAD

**Issue by romfreiman** [docker-library/kibana#54]
There was an error generating your report for the "STATS" dashboard: HeadlessError: Phantom immediately exited with: 127

Using latest docker both for kibana and for elastic

**Comment by yosifkit** [comment]
Perhaps we are missing the tool in the Kibana image that is used to generate the PDF?

**Comment by tianon** [comment]
Was there anything in the logs that might give a better clue as to what happened? (`docker logs container-name`)

**Comment by romfreiman** [comment]
Not really. Cannot see any exception there (neither in kibana nor in elastic containers).
This is the error i'm getting in the chrome browser:
There was an error generating your report for the "Dashboard" dashboard: HeadlessError: Phantom immediately exited with: 127

Not sure where from the the phantomjs is executed though.

**Comment by ynux** [comment]
same issue, with firefox.

**Comment by kailip** [comment]
Installing libfontconfig and libfreetype6 with apt-get inside the kibana docker container fixed the issue for me.

**Comment by ynux** [comment]
@kailip : This works for me, too, thanks a lot! How did you find out?

**Comment by bkoninski-neducatio** [comment]
@ynux https://github.com/ariya/phantomjs/issues/13597#issuecomment-143347477

**Comment by romfreiman** [comment]
Reporting: Error 403 Forbidden: Non-basic license has expired.
OK

**Comment by ynux** [comment]
https://www.elastic.co/subscriptions , Gold or Platinum required

**Comment by yosifkit** [comment]
I am :+1: to adding `libfontconfig` and `libfreetype6` to the image.
