### ISSUE TITLE
Serving kibana at port 443

### ISSUE THREAD

**Issue by anopheles** [docker-library/kibana#58]
I just encountered a problem with running the kibana docker container with port 443.

The only way possible was running kibana with root privileges. This is possible with gosu

`
FROM kibana:4.5.4

RUN chmod o+w /opt/kibana/optimize/.babelcache.json

CMD ["gosu", "root", "kibana"]
` 

The chmod was necessary because of this error

`fs.js:549
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: EACCES: permission denied, open '/opt/kibana/optimize/.babelcache.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.writeFileSync (fs.js:1156:15)
    at save (/opt/kibana/node_modules/babel-core/lib/api/register/cache.js:35:19)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickDomainCallback (node.js:390:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.j

`

The original error message was
`{"type":"log","@timestamp":"2016-10-12T13:52:53+00:00","tags":["fatal"],"pid":12,"level":"fatal","message":"listen EACCES 0.0.0.0:443","error":{"message":"listen EACCES 0.0.0.0:443","name":"Error","stack":"Error: listen EACCES 0.0.0.0:443\n    at Object.exports._errnoException (util.js:873:11)\n    at exports._exceptionWithHostPort (util.js:896:20)\n    at Server._listen2 (net.js:1237:19)\n    at listen (net.js:1286:10)\n    at net.js:1395:9\n    at nextTickCallbackWith3Args (node.js:453:9)\n    at process._tickDomainCallback (node.js:400:17)","code":"EACCES"}}
FATAL { [Error: listen EACCES 0.0.0.0:443]
  cause: 
   { [Error: listen EACCES 0.0.0.0:443]
     code: 'EACCES',
     errno: 'EACCES',
     syscall: 'listen',
     address: '0.0.0.0',
     port: 443 },
  isOperational: true,
  code: 'EACCES',
  errno: 'EACCES',
  syscall: 'listen',
  address: '0.0.0.0',
  port: 443 }
`

Is there a cleaner way to do this?

**Comment by tianon** [comment]
I would actually recommend using something like `nginx` in front of your `kibana` instance to accomplish this, especially since it includes code to open privileged ports as `root` and _then_ drop privileges, so that your running instance doesn't have `root` privileges anymore, which I'm not aware of Kibana having support for.

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
