### ISSUE TITLE
Kibana-5 fails to launch with custom-config - permission denied

### ISSUE THREAD

**Issue by jmkgreen** [docker-library/kibana#63]
In order to switch-off x-pack components (https://www.elastic.co/guide/en/x-pack/current/installing-xpack.html) I have supplied my own kibana.yaml file and provided the following 'CMD' instruction via a docker-compose.yaml file:

`kibana -c /usr/share/kibana/kibana-5.yaml`

On launch, I now get the following:

```
"type":"log","@timestamp":"2016-11-14T14:58:13Z","tags":["fatal"],"pid":13,"level":"fatal","message":"EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/monitoring.entry.js'","error":{"message":"EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/monitoring.entry.js'","name":"Error","stack":"Error: EACCES: permission denied, open '/usr/share/kibana/optimize/bundles/monitoring.entry.js'\n    at Error (native)","code":"EACCES"}}
```

Presumably something to do with the permissions run when the start-up script does not get run with `kibana` as the only argument?

**Comment by tianon** [comment]
Can you provide your full `docker run` line or `docker-compose.yml` file contents?

Are you doing any bind mounts or installing anything in your own `Dockerfile` which is `FROM` this image?

The [`docker-entrypoint.sh`](https://github.com/docker-library/kibana/blob/a50b513591761efb9c201933d0eb0296e8ae43af/5/docker-entrypoint.sh) script we use doesn't touch any file permissions, but it _does_ switch to the `kibana` user, so any files Kibana needs to access at runtime need at least read permissions for that user. :+1:

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
