### ISSUE TITLE
Docker ES and Kibana won't connect localhost

### ISSUE THREAD

**Issue by carnalim** [docker-library/kibana#65]
I run my docker images like such:

`docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 elasticsearch`

and 

`docker run -e ELASTICSEARCH_URL=http://localhost:9200 -p 5601:5601 -d kibana`

When I test Elastic:
```
http://localhost:9200/_cluster/health
{
  "cluster_name": "elasticsearch",
  "status": "green",
  "timed_out": false,
  "number_of_nodes": 1,
  "number_of_data_nodes": 1,
  "active_primary_shards": 0,
  "active_shards": 0,
  "relocating_shards": 0,
  "initializing_shards": 0,
  "unassigned_shards": 0,
  "delayed_unassigned_shards": 0,
  "number_of_pending_tasks": 0,
  "number_of_in_flight_fetch": 0,
  "task_max_waiting_in_queue_millis": 0,
  "active_shards_percent_as_number": 100
}
```

When I check Kibana:
` Unable to connect to Elasticsearch at http://localhost:9200`.

**Comment by yosifkit** [comment]
Correct, your host can access elasticsearch via `localhost` since you forwarded the ports with `-p 9200:9200 -p 9300:9300`, but kibana has its own network interface and localhost in the kibana container is just kibana, not your host.

You need to either give the ip of your elasticsearch container to kibana:

``` console
$ docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 --name elastic elasticsearch
$ ip="$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' elastic)"
$ docker run -e ELASTICSEARCH_URL="http://$ip:9200" -p 5601:5601 -d --name kib kibana
```

or use linking dns so that kibana can resolve a name to elasticsearch:

``` console
$ docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 --name elastic elasticsearch
$ docker run --link elastic:elastic-url -e ELASTICSEARCH_URL="http://elastic-url:9200" -p 5601:5601 -d --name kib kibana
```

or docker dns on a network:

``` console
$ docker network create elk
$ docker run -d -v "$PWD/esdata":/usr/share/elasticsearch/data -p 9200:9200 -p 9300:9300 --name elastic --net elk elasticsearch
$ docker run -e ELASTICSEARCH_URL="http://elastic:9200" -p 5601:5601 -d --name kib --net elk kibana
```

**Comment by carnalim** [comment]
On Elastic if I try the first set you give:

ERROR: name is not a recognized option

**Comment by carnalim** [comment]
Now I see this error:
`Could not find user-provided settings for Kibana 5.0.1`

**Comment by tianon** [comment]
@carnalim can you please provide more details for how we can replicate your new error?

I re-tried all of @yosifkit's three suggestions verbatim and every single one worked successfully. :confused:

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
