### ISSUE TITLE
dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:48468->[::1]:53: read: connection refused

### ISSUE THREAD

**Issue by IbrahimYahya** [docker-library/kibana#72]
When I tried to install x pack to elk using the bellow command I face error as shown bellow, so can you help me with this please.

sudo docker pull danielguerra/elasticsearch-x-pack       

Using default tag: latest
Pulling repository docker.io/danielguerra/elasticsearch-x-pack
Error while pulling image: Get https://index.docker.io/v1/repositories/danielguerra/elasticsearch-x-pack/images: dial tcp: lookup index.docker.io on [::1]:53: read udp [::1]:48468->[::1]:53: read: connection refused

**Comment by yosifkit** [comment]
This looks like a problem with pulling an image from the Docker Hub, rather than a problem with the kibana image.  It might be a transitory problem that will resolve itself, but if you need help your best bet is sending an email to `support@docker.com`.
