### ISSUE TITLE
Kibana not connecting to Elasticsearch with username and password

### ISSUE THREAD

**Issue by cspnanda** [docker-library/kibana#75]
We tried running the container as 

    docker run -e ELASTICSEARCH_URL='http://a.b.c.d:9200'
                       -e ELASTICSEARCH_USERNAME='elastic' 
                       -e ELASTICSEARCH_PASSWORD='secret!' 
                       -p 127.0.0.1:5601:5601 -d kibana:5.2.0

When we browse Kibana UI we see **plugin:elasticsearch@5.2.0     Authentication Exception**

we can reach ES by curl directly just fine

    $ curl -u elastic:secret! http://a.b.c.d:9200/_cat/indices?v

Inside container variables are set just fine.

    $ docker exec <cont name> bash -c 'echo "$ELASTICSEARCH_URL,$ELASTICSEARCH_USERNAME,$ELASTICSEARCH_PASSWORD"'

*http://a.b.c.d:9200,elastic,secret!*

But if we look at 

    $ docker exec <cont name> bash -c 'cat /etc/kibana/kibana.yml'

    elasticsearch.url: 'http://a.b.c.d:9200' => this is fine
    #elasticsearch.username: "user" . => This is not set
    #elasticsearch.password: "pass" . => This is not set

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
