### ISSUE TITLE
Export log from kibana container to host machine

### ISSUE THREAD

**Issue by parthtrivedi2492** [docker-library/kibana#77]
Hello All,

I want to change logging for kibana docker. 

By default kibana docker writes output to stdout but after changing kibana.yml file , I am changing destination path to location: /var/log/kibana/kibana.log ( I have created folder /var/log/kibana in docker container)

Issue:
If I use root access to folder (/var/log/kibana) I am not able to write logs in this folder. So that I changed permission of this folder to kibana user and I can able to write files to this folder but with kibana user I am not able to mount directory from docker container to my host file system.

Any idea or ideal suggestion to write log files from kibana container to host machine ?

Regards,
Parth

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
