### ISSUE TITLE
kibana red status due to ES Request Timeout

### ISSUE THREAD

**Issue by nico2610** [docker-library/kibana#79]
Hello,

I'm running kibana:4.5 docker image on Openshift. It works but after minutes (not always after the same time) I got this message : 

`{"type":"log","@timestamp":"2017-03-28T13:25:48+00:00","tags":["status","plugin:elasticsearch","error"],"pid":51,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}`

after that this status flaps :

`{"type":"log","@timestamp":"2017-03-28T13:25:48+00:00","tags":["status","plugin:elasticsearch","error"],"pid":51,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2017-03-28T13:26:21+00:00","tags":["status","plugin:elasticsearch","info"],"pid":51,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"}
{"type":"log","@timestamp":"2017-03-28T13:26:27+00:00","tags":["status","plugin:elasticsearch","error"],"pid":51,"name":"plugin:elasticsearch","state":"red","message":"Status changed from green to red - Request Timeout after 3000ms","prevState":"green","prevMsg":"Kibana index ready"}
{"type":"log","@timestamp":"2017-03-28T13:26:55+00:00","tags":["status","plugin:elasticsearch","info"],"pid":51,"name":"plugin:elasticsearch","state":"green","message":"Status changed from red to green - Kibana index ready","prevState":"red","prevMsg":"Request Timeout after 3000ms"} `

I verified my Elasticsearch cluster and it's up and running, reachable by network, cluster ehealth status green, nothing in the logs. 
When I want to access to kibana, I'm directly redirected to the status find, mentionning the red status due to the request Timeout after 3000ms

I tried to increase the timeout > 3000ms by changing elasticsearch.requestTimeout and elasticsearch.pingTimeout in kibana.yaml to find a workaround but it doesn't seem take it into account because the status page still show Request Timeout after 3000ms.

**Comment by jayannah** [comment]
+1.. same issue I faced today.. But, it self healed after 30min.. not sure about the reason.

**Comment by fbarbeira** [comment]
+1

**Comment by nico2610** [comment]
I built my own Kibana image to solve the problem

**Comment by tianon** [comment]
This image is officially deprecated in favor of upstream's images (see https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html).

For more information, please see docker-library/elasticsearch#160, docker-library/docs#842, and docker-library/docs#945.

> This image has been deprecated in favor of the [official `kibana` image](https://www.elastic.co/guide/en/kibana/current/_pulling_the_image.html) provided and maintained by [elastic.co](https://www.elastic.co/). The upstream images are available to pull via `docker.elastic.co/kibana/kibana:[version]` like `5.4.2`. The images found here will receive no further updates once the `5.6.0` release is available upstream. Please adjust your usage accordingly.
> 
> Elastic provides open-source support for Kibana via the [elastic/kibana GitHub repository](https://github.com/elastic/kibana) and the Docker image via the [elastic/kibana-docker GitHub repository](https://github.com/elastic/kibana-docker), as well as community support via its [forums](https://discuss.elastic.co/c/kibana).

Thanks!
