### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [docker-library/kibana#81]
I want to build this image on arm64 architecture but I don't found some package support arm64 at https://artifacts.elastic.co/packages/5.x/apt/dists/stable/Release . So I want to know this image whether or not support arm64 architecture.

**Comment by tianon** [comment]
As noted in the image description and the repository readme, this image is deprecated (and so we will not be implementing multi-architecture support here, or in `logstash` or `elasticsearch`).  See https://github.com/docker-library/elasticsearch/pull/160 for more details.

**Comment by longquan7** [comment]
@tianon OK,thanks
