### ISSUE TITLE
Documentation provides a link that does NOT exist

### ISSUE THREAD

**Issue by websecusa** [docker-library/kibana#90]
The below URL provides a link that is incorrect

https://github.com/docker-library/kibana/blob/014d49e819ccf947882b6c9c809f62896f534dae/6/Dockerfile

Please see line 11
# For Elasticsearch documentation visit https://www.elastic.co/guide/en/kibana/reference/current/docker.html

**Comment by tianon** [comment]
Doh, looks like that should be https://www.elastic.co/guide/en/kibana/current/docker.html -- good catch!
